[package]
name = "notify"
version = "0.1.0"
authors = ["Gabe <finkegabriel>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
serde_derive = "1.0.104"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"


